<?php

/**
 * Created by PhpStorm.
 * User: itaifeng
 * Date: 2016/10/30
 * Time: 上午 10:15
 */
class FirstTest extends PHPUnit_Framework_TestCase
{
    public function testFirst()
    {
        $joel = new App\Workshop\Joel();

        $this->assertEquals('joel', $joel->getName());
    }

    /**
     * @return array
     */
    public function testCalculator()
    {
        $calculator = new App\Workshop\Calculator();
        $actual = $calculator->add(1, 2);

        $this->assertEquals(3, $actual);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}